list_of_address = [
        (
            "Serniczkowa",
            "4B",
            2,
            "Krakow",
            "02-326"
        ),
        (
            "Pierniczkowa",
            "289",
            55,
            "Gdansk",
            "02-326"
        ),
        (
            "Pierniczkowa",
            "289",
            55,
            "Gdansk",
            "02-326"
        ),
        (
            "Pierniczkowa",
            "289",
            55,
            "Gdansk",
            "02-326"
        ),
        (
            "Barszczykowa",
            "234",
            5,
            "Rzeszow",
            "37-326"
        ),
        (
            "Uszkowa",
            "43H",
            5,
            "Wroclaw",
            "02-326"
        ),
        (
            "Uszkowa",
            "43H",
            5,
            "Wroclaw",
            "02-326"
        ),
        (
            "Uszkowa",
            "43H",
            5,
            "Wroclaw",
            "02-326"
        ),
        (
            "Cukierkowa",
            "23",
            5,
            "Poznan",
            "02-326"
        )
    ]
list_of_none = []
for item in list_of_address:
    if item in list_of_none:
        continue
    else:
        list_of_none.append(item)
print(list_of_none)